### PR TITLE
Added support for Docker.

### PR DESCRIPTION
**Pull request by adec**
Added Dockerfile to create image based on openjdk:8-jre-alpine.  Amended README.md to include details on how to build and run the docker image.

### CODE REVIEW

**Comment by hardillb** [comment]
Thanks for this

Any chance of having a look at converting it to the maven:alpine-onbuild docker parent container, then the compile step gets done as part of the docker build? https://hub.docker.com/_/maven/

**Comment by adec** [comment]
No problem. I had considered it but originally decided against it as I assumed the image will be bigger.  However in reality the difference will probably be negligible and worth it for ease of use.

**Comment by adec** [comment]
You may want to hold off merging this request at the moment. I reworked the dockerfile as requested and tested the basic build. However I wasn't able to test the full functionality. I'll test it out more fully this evening and give you the nod when it's done.

**Comment by hardillb** [comment]
Cool, thanks for the heads up.

**Comment by hardillb** [comment]
I'll have a look at the maven doc to see if I can get it to generate a shell script with the target jar file name built in so we don't have to keep bumping the version in the Dockerfile each time we do a release

**Comment by adec** [comment]
If I've committed the right version of the Dockerfile I've fixed that one.  I was struggling with the same thing earlier.  

I was originally going to use the Exec Maven plugin but was struggling with passing additional parameters. 

Instead I found a solution by using the CLASSPATH to search for the Main method so I don't have to reference the Jar file directly.

**Comment by adec** [comment]
Okay I committed the wrong Dockerfile. I'll update it again.

**Comment by adec** [comment]
Just finished testing against my Tradfri gateway & MQTT broker - all good. ;-)

**Pull request merged**
