### PR TITLE
Implement color changing

### PR DESCRIPTION
**Pull request by r41d**
Better merge my other pull request with the Tradfri Constancts first, as this builds on top of it

### CODE REVIEW

**Comment by hardillb** [comment]
Change color to temperature as we don't know if IKEA will release RGB bulbs in the future

**Comment by r41d** [comment]
Now that you mention it, the COLOR_X and COLOR_Y may be for actual RGB color.
Will do that change soon...

**Comment by r41d** [comment]
OK, I changed it to temperature. I retained the variable name COLOR in the Constants, because it's called like that in the IPSOObjects class from the official Tradfri Anrdoid App.

**Comment by hardillb** [comment]
I'm just about to add a license to this lot (Apache-2.0) and I'm a bit wary of the constants file, which as it stands the comment at the top basically says it was ripped off from the IKEA Android app, which we have to assume is not Open Source licensed.

Also the long stack of unused constants doesn't help with claiming it was built from available info to do what was needed.

**Comment by r41d** [comment]
Not sure how much intellectual property a random collections of numbers contains (some also come from official standardization documents) but I mostly aggree on that one.
I'm personally fine with Apache 2 License for my submitted code.
What would you suggest? One way to do it is kicking all unsed constants and including them one by one, if needed. They are all contained for reference [here](http://sprunge.us/CCQF)

**Comment by hardillb** [comment]
Trim the extra ones, we can add what we need later and maybe try to be a little subtler with the header comment. Then it all looks good and I'll merge.

**Comment by r41d** [comment]
Hope I achieved subtler :)

**Pull request merged**
